function:
  name: omni-coe-table-reader-${self:provider.stage}
  handler: src/omniCoeTable/index.handler
  description: Omni Coe Table Reader
  package:
    patterns:
      - "!**/*"
      - "src/omniCoeTable/*.js"
      - "src/commonFunctions/**"
  runtime: nodejs18.x
  events:
    - sqs:
        arn: { "Fn::GetAtt": ["omniCoeTableReaderQueue", "Arn"] }
        batchSize: 10
  layers:
    - !Ref OmniDWHLayerLambdaLayer
  environment:     
    ERROR_SNS_ARN: ${ssm:/omni-reports/${self:provider.stage}/error-notification/sns/arn} 
    TRACKING_NOTES_TABLE_NAME: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/tracking-notes/ddb.tableName}
    SHIPMENT_HEADER_TABLE_NAME: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-header/ddb.tableName}  
    DATE_THRESHOLD: '2023-01-01'