function:
  name: omni-coe-table-reader-${self:provider.stage}
  handler: src/omniCoeTable/index.handler
  description: Omni Coe Table Reader
  package:
    patterns:
      - "!**/*"
      - "src/omniCoeTable/*.js"
      - "src/commonFunctions/**"
  runtime: nodejs18.x
  events:
    - sqs:
        arn: arn:aws:sqs:us-east-1:332281781429:omni-coe-table-reader-queue-dev
        batchSize: 10
  layers:
    - !Ref OmniDWHLayerLambdaLayer
  environment:      
    TRACKING_NOTES_TABLE_NAME: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/tracking-notes/ddb.tableName}
    SHIPMENT_HEADER_TABLE_NAME: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-header/ddb.tableName}  
    # TRACKING_NOTES_TABLE_NAME: omni-wt-rt-tracking-notes-dev
    # SHIPMENT_HEADER_TABLE_NAME: omni-wt-rt-shipment-header-dev
    DATE_THRESHOLD: '2023-01-01'