function:
  name: omni-coe-table-batch-trigger-${self:provider.stage}
  handler: src/omniCoeTable/trigger-function.handler
  description: Omni Coe Table  
  package:
    patterns:
      - "!**/*"
      - "src/omniCoeTable/*.js"
      - "src/commonFunctions/**"
  runtime: nodejs18.x
  layers:
    - !Ref OmniDWHLayerLambdaLayer
  # events:
  #   - schedule: cron(0 4,16 * * ? *)
  environment:
    JOB_DEFINITION: !Ref OmniCoeTableHistoricalDataJobDefinition
    JOB_NAME: omni-coe-table-historical-data-job-${self:provider.stage}
    JOB_QUEUE: !Ref OmniCoeTableHistoricalDataJobQueue