OmniCoeTableBatchHistoricalDataServiceRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
      - Effect: Allow
        Principal:
          Service: batch.amazonaws.com
        Action: sts:AssumeRole
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole

OmniCoeTableHistoricalDataComputeEnvironment:
  Type: AWS::Batch::ComputeEnvironment
  Properties:
    ComputeEnvironmentName: omni-coe-table-historical-data-env-${self:provider.stage}
    Type: MANAGED
    ServiceRole:
      Ref: OmniCoeTableBatchHistoricalDataServiceRole
    ComputeResources:
      MaxvCpus: 256
      SecurityGroupIds:
        - ${ssm:/omni-dw/${self:provider.stage}/lambda/sgId}
      Type: FARGATE
      Subnets:
        - ${ssm:/omni-dw/${self:provider.stage}/lambda/subnetA}
    State: ENABLED