# OmniCoeTableJobBatchTaskExecutionRole:
#   Type: AWS::IAM::Role
#   Properties:
#     RoleName: omni-coe-table-role-${self:provider.stage}
#     AssumeRolePolicyDocument:
#       Statement:
#         - Effect: Allow
#           Principal:
#             Service: [ecs-tasks.amazonaws.com]
#           Action: ["sts:AssumeRole"]
#     Path: /
#     Policies:
#       - PolicyName: AmazonECSTaskExecutionRolePolicy
#         PolicyDocument:
#           Statement:
#             - Effect: Allow
#               Action:
#                 - "ecr:GetAuthorizationToken"
#                 - "ecr:BatchCheckLayerAvailability"
#                 - "ecr:GetDownloadUrlForLayer"
#                 - "ecr:BatchGetImage"
#                 - "logs:CreateLogStream"
#                 - "logs:PutLogEvents"
#                 - "sns:Publish"
#               Resource: "*"
#       - PolicyName: omni-coe-table-mysql-policy-${self:provider.stage}
#         PolicyDocument:
#           Statement:
#             - Effect: Allow
#               Action:
#                 - rds-db:connect
#                 - rds:DescribeDBInstances
#                 - rds:ListTagsForResource
#                 - mysql:Query
#                 - mysql:Select
#                 - mysql:Insert
#                 - mysql:Update
#                 - mysql:Delete
#               Resource: "*"

# OmniCoeTableJobDefinition:
#   Type: AWS::Batch::JobDefinition
#   Properties:
#     JobDefinitionName: omni-coe-table-job-definition-${self:provider.stage}
#     Type: container
#     RetryStrategy:
#       Attempts: 1
#     PlatformCapabilities:
#       - FARGATE
#     ContainerProperties:
#       Command:
#         - node
#         - batch.js
#       ResourceRequirements:
#         - Value: 1
#           Type: VCPU
#         - Value: 2048
#           Type: MEMORY
#       FargatePlatformConfiguration:
#         PlatformVersion: 1.3.0
#       LogConfiguration:
#         LogDriver: awslogs
#         Options:
#           awslogs-group: !Ref OmniCoeTableBatchLogGroup
#           awslogs-region: !Ref AWS::Region
#           awslogs-stream-prefix: omni-coe-table-batch-logs
#       ExecutionRoleArn: !GetAtt 'OmniCoeTableJobBatchTaskExecutionRole.Arn'
#       JobRoleArn: !GetAtt 'OmniCoeTableJobBatchTaskExecutionRole.Arn'
#       Image:
#         Fn::Join:
#           - ""
#           - - Ref: AWS::AccountId
#             - .dkr.ecr.
#             - Ref: AWS::Region
#             - ".amazonaws.com/omni-coe-table-ecr-repo-"
#             - ${self:provider.stage}
#             - ":"
#             - latest
#       NetworkConfiguration:
#         AssignPublicIp: ENABLED
# OmniCoeTableBatchLogGroup:
#   Type: AWS::Logs::LogGroup
#   Properties:
#     LogGroupName: omni-coe-table-batch-log-group-${self:provider.stage}
#     RetentionInDays: 7
