omniCoeTableStagingTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: omni-coe-table-staging-table-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S  
    KeySchema:
      - AttributeName: id
        KeyType: HASH 
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES